# Generated by Django 3.2.21 on 2023-09-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
